language: cpp
dist: trusty
compiler:
  - gcc
before_script:
  - chmod +x test/prep.sh
  - git clone https://github.com/takashiro/karuta-server
  - cd karuta-server
  - make
  - cd ..
script:
  - make -j 8 KARUTADIR=karuta-server
  - make test -j 8 KARUTADIR=karuta-server
